# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='IndexIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'index_index',
            },
        ),
        migrations.CreateModel(
            name='QueryQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'query_query',
            },
        ),
        migrations.CreateModel(
            name='SystemAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('sort', models.SmallIntegerField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('create_by', models.BigIntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'system_auth',
            },
        ),
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'system_category',
            },
        ),
        migrations.CreateModel(
            name='SystemClause',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('clause', models.CharField(max_length=2000)),
            ],
            options={
                'managed': False,
                'db_table': 'system_clause',
            },
        ),
        migrations.CreateModel(
            name='SystemCommonSensitiveWords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30)),
                ('advice_id', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'system_common_sensitive_words',
            },
        ),
        migrations.CreateModel(
            name='SystemDistrict',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'system_district',
            },
        ),
        migrations.CreateModel(
            name='SystemImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='upload')),
            ],
            options={
                'managed': False,
                'db_table': 'system_image',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
                ('node', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'system_log',
            },
        ),
        migrations.CreateModel(
            name='SystemMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pid', models.BigIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=400)),
                ('params', models.CharField(blank=True, max_length=500, null=True)),
                ('target', models.CharField(max_length=20)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('create_by', models.BigIntegerField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'system_menu',
            },
        ),
        migrations.CreateModel(
            name='SystemOtherSensitiveWords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('district_id', models.SmallIntegerField()),
                ('category_id', models.SmallIntegerField()),
                ('word', models.CharField(max_length=30)),
                ('advice_id', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'system_other_sensitive_words',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('qq', models.CharField(blank=True, max_length=16, null=True)),
                ('mail', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('login_num', models.BigIntegerField(blank=True, null=True)),
                ('login_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('authorize', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('create_by', models.BigIntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'system_user',
            },
        ),
        migrations.CreateModel(
            name='SystemUserCharge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('consume', models.FloatField(blank=True, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('overage', models.FloatField()),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'system_user_charge',
            },
        ),
        migrations.CreateModel(
            name='SystemUserSimple',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'system_user_simple',
            },
        ),
    ]
